version: "3"
name: "fishing"
services:
  postgres:
    build:
      context: ./db/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db/data/postgres/:/var/lib/postgresql/data
  web-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
