CREATE TABLE accounts (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255),
  password VARCHAR(60),
  created_at TIMESTAMP
  WITH
    TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
  WITH
    TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
